# .travis.yml file based on:
# https://gist.github.com/dan-blanchard/7045057

language: python
python:
  - "2.7"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION numpy bokeh enaml atom h5py scipy networkx future jupyter
  - pip install coveralls

# use conda to install packages
install:
 # Coverage packages are on my binstar channel
  - pip install watchdog
  - pip install git+https://github.com/BBN-Q/QGL.git

# execute scripts
script:
  - coverage run -m unittest discover
after_script:
  - coveralls

# necessary to run on new container-based infrastructure
sudo: false
